Repository omg/community-bots, pull requests merged in 2024-01, with the labels that each got.

#141 Allow the magic8 mention command to activate with a trailing question mark
  lame-bot/commands/mentions/magic8.ts
Labels: priority:3, type:input

#143 Add "௵" and "௸" to banned characters in names
  lame-bot/src/word-bomb-mini.ts
Labels: type:cosmetic, priority:3

#146 change vivi formating
  src/dictionary/dictionary.ts
  src/sleuth.ts
  src/utils.ts
  vivi/src/client.ts
Labels: type:code-quality, priority:3

#145 Change deploy to release
  .github/workflows/push_to_release.yml
Labels: type:code-quality

#147 New regex system
  lame-bot/src/word-bomb-mini.ts
  src/command-handler.ts
  src/database/db.ts
  src/dictionary/dictionary.ts
  src/dictionary/solve-worker.ts
  src/emoji-renderer.ts
  src/regex.ts
  src/utils.ts
  vivi/commands/count.ts
  vivi/commands/solve.ts
Labels: priority:2, type:behavioral, area:regex
